# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from notalking.v1 import core_pb2 as notalking_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notalking/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreBridgeStub(object):
    """Core Intelligence bridge -- synchronous RPCs from Intelligence to Core (SPEC 5, 6).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/notalking.v1.CoreBridge/HealthCheck',
                request_serializer=notalking_dot_v1_dot_core__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetNoteContext = channel.unary_unary(
                '/notalking.v1.CoreBridge/GetNoteContext',
                request_serializer=notalking_dot_v1_dot_core__pb2.GetNoteContextRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.GetNoteContextResponse.FromString,
                _registered_method=True)
        self.SearchNotes = channel.unary_unary(
                '/notalking.v1.CoreBridge/SearchNotes',
                request_serializer=notalking_dot_v1_dot_core__pb2.SearchNotesRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.SearchNotesResponse.FromString,
                _registered_method=True)
        self.GetNoteContent = channel.unary_unary(
                '/notalking.v1.CoreBridge/GetNoteContent',
                request_serializer=notalking_dot_v1_dot_core__pb2.GetNoteContentRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.GetNoteContentResponse.FromString,
                _registered_method=True)
        self.CreateNote = channel.unary_unary(
                '/notalking.v1.CoreBridge/CreateNote',
                request_serializer=notalking_dot_v1_dot_core__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.CreateNoteResponse.FromString,
                _registered_method=True)
        self.UpdateNote = channel.unary_unary(
                '/notalking.v1.CoreBridge/UpdateNote',
                request_serializer=notalking_dot_v1_dot_core__pb2.UpdateNoteRequest.SerializeToString,
                response_deserializer=notalking_dot_v1_dot_core__pb2.UpdateNoteResponse.FromString,
                _registered_method=True)


class CoreBridgeServicer(object):
    """Core Intelligence bridge -- synchronous RPCs from Intelligence to Core (SPEC 5, 6).
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNoteContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNoteContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.HealthCheckRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetNoteContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNoteContext,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.GetNoteContextRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.GetNoteContextResponse.SerializeToString,
            ),
            'SearchNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNotes,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.SearchNotesRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.SearchNotesResponse.SerializeToString,
            ),
            'GetNoteContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNoteContent,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.GetNoteContentRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.GetNoteContentResponse.SerializeToString,
            ),
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.CreateNoteRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.CreateNoteResponse.SerializeToString,
            ),
            'UpdateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNote,
                    request_deserializer=notalking_dot_v1_dot_core__pb2.UpdateNoteRequest.FromString,
                    response_serializer=notalking_dot_v1_dot_core__pb2.UpdateNoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notalking.v1.CoreBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notalking.v1.CoreBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreBridge(object):
    """Core Intelligence bridge -- synchronous RPCs from Intelligence to Core (SPEC 5, 6).
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/HealthCheck',
            notalking_dot_v1_dot_core__pb2.HealthCheckRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNoteContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/GetNoteContext',
            notalking_dot_v1_dot_core__pb2.GetNoteContextRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.GetNoteContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/SearchNotes',
            notalking_dot_v1_dot_core__pb2.SearchNotesRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.SearchNotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNoteContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/GetNoteContent',
            notalking_dot_v1_dot_core__pb2.GetNoteContentRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.GetNoteContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/CreateNote',
            notalking_dot_v1_dot_core__pb2.CreateNoteRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.CreateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notalking.v1.CoreBridge/UpdateNote',
            notalking_dot_v1_dot_core__pb2.UpdateNoteRequest.SerializeToString,
            notalking_dot_v1_dot_core__pb2.UpdateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
